INSERT INTO CARACTERISTICA VALUES (1, 'CORRECTO');
INSERT INTO CARACTERISTICA VALUES (2, 'HOJAS EN BLANCO');
INSERT INTO CARACTERISTICA VALUES (3, 'ILEGIBLE');
INSERT INTO CARACTERISTICA VALUES (4, 'INCOMPLETO');
INSERT INTO CARACTERISTICA VALUES (5, 'SIN TX');

INSERT INTO CIRCUITO VALUES (1, 'Primer Circuito Judicial de San José');
INSERT INTO CIRCUITO VALUES (2, 'Segundo Circuito Judicial de San José');

INSERT INTO DESPACHO VALUES ('0001', 2, 'Pruebas de Santiago');

INSERT INTO PRIORIDAD VALUES (1, 'NORMAL');
INSERT INTO PRIORIDAD VALUES (2, 'URGENTE');

INSERT INTO USUARIO VALUES ('imendezca', '0001', '12345', CONVERT(DATE, '2019-10-16'));

INSERT INTO CONSECUTIVO (IDConsecutivo, Periodo, NumConsecutivo) VALUES ('FAX', '2019',0);

