-- Created by Vertabelo (http://vertabelo.com)
-- Last modification date: 2019-10-21 19:36:45.323

-- foreign keys
ALTER TABLE DESPACHO DROP CONSTRAINT DESPACHO_CIRCUITO;

ALTER TABLE FAX DROP CONSTRAINT FAX_CARACTERISTICA;

ALTER TABLE FAX DROP CONSTRAINT FAX_DESPACHO;

ALTER TABLE FAX DROP CONSTRAINT FAX_PRIORIDAD;

ALTER TABLE FAX DROP CONSTRAINT FAX_USUARIO_COMPRUEBA;

ALTER TABLE FAX DROP CONSTRAINT FAX_USUARIO_INGRESO;

ALTER TABLE FAX DROP CONSTRAINT FAX_USUARIO_RECIBIDO;

ALTER TABLE USUARIO DROP CONSTRAINT USUARIO_DESPACHO;

ALTER TABLE usuario_rol DROP CONSTRAINT usuario_rol_ROL;

ALTER TABLE usuario_rol DROP CONSTRAINT usuario_rol_USUARIO;

-- tables
DROP TABLE BITACORA;

DROP TABLE CARACTERISTICA;

DROP TABLE CIRCUITO;

DROP TABLE CONSECUTIVO;

DROP TABLE DESPACHO;

DROP TABLE ERROR;

DROP TABLE FAX;

DROP TABLE PRIORIDAD;

DROP TABLE ROL;

DROP TABLE USUARIO;

DROP TABLE usuario_rol;

-- End of file.

